version: '3.8'

services:
  config:
    image: ${DOCKER_ID}/config-anamensis:${TAG}
    ports:
      - "8077:8080"
    networks:
      - anamensis
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 60s
        delay: 10s
        order: start-first
      rollback_config:
        delay: 0s
        parallelism: 1
        failure_action: continue
        order: start-first
    healthcheck:
      test: "curl http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure
    secrets:
      - source: config_anamensis_secret_config
        target: /application.yml
      - source: config_anamensis_secret_keystore
        target: /anamensis.jks

  server:
    image: ${DOCKER_ID}/server-anamensis:${TAG}
    ports:
      - "8080:8080"
    networks:
      - anamensis
    links:
      - config-anamensis
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config:8080
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 60s
        delay: 10s
        order: start-first
      rollback_config:
        delay: 0s
        parallelism: 1
        failure_action: continue
        order: start-first
    healthcheck:
      test: "curl http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure
    secrets:
      - source: server_anamensis_secret_config
        target: /application.yml

#  batch-anamensis:
#    image: batch-anamensis:${TAG}
#    networks:
#      - anamensis
#    ports:
#      - "8088:8080"
#    deploy:
#      update_config:
#        parallelism: 1
#        failure_action: rollback
#        monitor: 60s
#        delay: 10s
#        order: start-first
#      rollback_config:
#        delay: 0s
#        parallelism: 1
#        failure_action: continue
#        order: start-first
#    healthcheck:
#      test: "curl http://localhost:8080/actuator/health | grep UP || exit 1"
#      interval: 60s
#      timeout: 5s
#      retries: 3
#      start_period: 10s
#    restart: on-failure
#    secrets:
#      - source: batch_anamensis_secret_config
#        target: /application.yml

  nextjs:
#    depends_on:
#      - server-anamensis
    image: ${DOCKER_ID}/nextjs-anamensis:${TAG}
    links:
      - server-anamensis
    environment:
      - NEXT_PUBLIC_SERVER=http://server:8080
    env_file:
      - nextjs.env
    networks:
      - anamensis
    ports:
      - "${PORT}:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 60s
        delay: 10s
        order: start-first
      rollback_config:
        delay: 0s
        parallelism: 1
        failure_action: continue
        order: start-first
    healthcheck:
      test: "curl http://localhost:3000 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure

networks:
  anamensis:
    driver: overlay

secrets:
  server_anamensis_secret_config:
    external: true

  config_anamensis_secret_config:
    external: true

  config_anamensis_secret_keystore:
    external: true

  batch_anamensis_secret_config:
    external: true