version: '3.7'

services:
  anamensis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR: server-anamensis-${TAG}
    image: anamensis:${TAG}
    networks:
      - net
    ports:
      - "18080:8080"
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 20s
        delay: 20s
        order: start-first
      rollback_config:
        delay: 0s
        parallelism: 1
        failure_action: continue
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health", "||", "grep UP", "||", "exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  net:
    driver: overlay
    attachable: true
#    external: true