version: '3.8'

services:
  nextjs-anamensis:
    image: ${DOCKER_ID}/nextjs-anamensis:${TAG}
    networks:
      - anamensis
    ports:
      - "${PORT}:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 60s
        delay: 10s
        order: start-first
      rollback_config:
        delay: 0s
        parallelism: 1
        failure_action: continue
        order: start-first
    healthcheck:
      test: "curl http://localhost:3000 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure

networks:
  anamensis:
    external: true
