version: '3.8'

services:
  server-anamensis:
    build:
      context: .
      dockerfile: Server-Dockerfile
      args:
        JAR: server-anamensis-${TAG}
    image: server-anamensis:${TAG}
    networks:
      - net
    ports:
      - "${PORT}:8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 60s
        delay: 10s
        order: start-first
      rollback_config:
        delay: 0s
        parallelism: 1
        failure_action: continue
        order: start-first
    healthcheck:
      test: "curl http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: on-failure

networks:
  net:
    driver: overlay
