mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.anamensis.server.entity, com.anamensis.server.resultMap, com.anamensis.server.typeHandler
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: "null"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: user
    password: password
  webflux:
    multipart:
      max-parts: -1
      file-storage-directory: classpath:static/upload
      max-in-memory-size: 2MB
  servlet:
    multipart:
      max-request-size: 10MB

  profiles:
    active: local
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

  session:
    redis:
      flush-mode: on_save
      namespace: spring

  cloud:
    aws:
      credentials:
        access-key: access-key
        secret-key: scret-key
      s3:
        enabled: true
        region: ap-northeast-2

logging:
  level:
    mapper:
      mybatis: debug

email:
  host: smtp.gmail.com
  port: 587
  username: username
  password: password

file:
  upload-dir: /Users/username/Downloads/upload

pageable:
  page: 1
  size: 20

## 예제
jwt:
  secret: c2R2c2RsdmlqZHM7dmlqYTsnb3NkaWpmYW85d2V1cndhZWxrbnZtbC54Y252bGl6dXhjaHZwOHN2OGloamFzO2RsdmtuYW1zO2RsaWZqYW9zZGZ1OTA4OXUyMzA0Mmpsa25tLnZseGNudnppaHNkbztmaHNvZGZhZGZhZmJ2enhjYnp2YnpkZmJmZA

aws:
  ses:
    access-key: access-key
    secret-key: secret-key
    region: us-west-2
    from: from@email.com
