mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.anamensis.server.entity, com.anamensis.server.resultMap, com.anamensis.server.typeHandler
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: "null"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: user
    password: password
  webflux:
    multipart:
      max-parts: -1
      file-storage-directory: classpath:static/upload

  profiles:
    active: local

logging:
  level:
    mapper:
      mybatis: debug

email:
  host: smtp.gmail.com
  port: 587
  username: username
  password: password

file:
  upload-dir: /Users/username/Downloads/upload