import "./init.css"
import {Metadata} from "next";
import NavMain from "@/app/NavMain";
import {ErrorBoundary} from "next/dist/client/components/error-boundary";
import Error from "@/app/error";

export const metadata : Metadata = {
  title: 'Anamensis',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
	<html lang="ko">
        <body>
            <NavMain />
            <div>
                <ErrorBoundary errorComponent={Error}>
                    {children}
                </ErrorBoundary>
            </div>
        </body>
	</html>
  )
}
