import "./init.css"
import {Metadata} from "next";
import NavMain from "@/app/NavMain";
import {cookies} from "next/headers";

export const metadata : Metadata = {
  title: 'Anamensis',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
	<html lang="ko">
        <body>
            <NavMain cookie={cookies} />
            <div>
                {children}
            </div>
        </body>
	</html>
  )
}
