name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      
      - name: print branch
        run: echo ${{ github.ref }}
      - name: print push branch name
        run: echo ${{ github.event_name }}

      - name: Build the Docker image
        run: ./build.sh server x.x.1 ${{ secrets.DOCKER_ID }}
