name: Docker Image CI

on:
  push:
    branches:
      - site/release/*
      - config/release/*
      - batch/release/*
env:
  SERVICE: $(echo ${{ github.ref_name }} | cut -f1 -d'/')
  VERSION: $(echo ${{ github.ref_name }} | cut -f3 -d'/')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Decode and set .env.local
        run: echo "${{ secrets.NEXTJS_ENV }}" | base64 --decode > ./client/.env.local

      - name: Decode and set application.yml
        run: echo "${{ secrets.SITE_TEST_CONFIG }}" | base64 --decode > ./server/src/main/resources/application.yml

      - name: Next.js install
        run: npm install --prefix ./client

      - name: Build the Next.js
        run: npm run build --prefix ./client

      - name: Build the Docker image
        run: ./build.sh ${{ env.SERVICE }} ${{ env.VERSION }} ${{ secrets.DOCKER_ID }} ${{ secrets.BASE_ID }}

      - name: Compress test report
        run: tar -czvf ${{ env.VERSION }}-test-report.tar.gz ./server/build/reports/tests

      - name: Upload Springboot - test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ${{ env.VERSION}}-test-report.tar.gz