name: Docker Image CI

on:
  push:
    branches:
      - server/release/*
      - nextjs/release/*
      - config/release/*
      - batch/release/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE: $(echo ${{ github.ref_name }} | cut -f1 -d'/')
      VERSION: $(echo ${{ github.ref_name }} | cut -f3 -d'/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Decode and set .env.local
        run: echo "${{ secrets.NEXTJS_ENV }}" | base64 --decode > ./client/.env.local

      - name: Build the Docker image
        run: ./build.sh ${{ env.SERVICE }} ${{ env.VERSION }} ${{ secrets.DOCKER_ID }}